# Databricks notebook source
import pyspark.sql.functions as F

# COMMAND ----------

# DBTITLE 1,Data aggregation
"""
    Gold table will be generated by aggregating the silver table by country, state, city, and brewery type.
    The silver table will be filtered to remove records with encoding issues and records without an address. (Business Definition)
"""

df_gold = (
    spark.table("md_silver.tb_dim_brewery")
    .filter((F.col("has_proper_encoding") == True) & (F.col("has_address") == True))
    .groupBy("country", "state", "city", "brewery_type")
    .agg(
        F.countDistinct("id").alias("brewery_count")
    )
    .withColumn("last_update", F.current_timestamp())
)

# COMMAND ----------

# DBTITLE 1,Validation
"""
    This step is responsible for validating the data quality of the Gold table.
    The validation is performed by checking if the dataset is empty;
"""

if df_gold.count() == 0:
    raise Exception("Empty aggregation")

# COMMAND ----------

# DBTITLE 1,Save: tb_agg_brewery_location
# Saving with FULL REFRESH on Gold Table
(
    df_gold
    .write
    .format("delta")
    .mode("overwrite")
    .saveAsTable("md_gold.tb_agg_brewery_location")
)

# COMMAND ----------

# DBTITLE 1,Optmize Gold
spark.sql("""
OPTIMIZE md_gold.tb_agg_brewery_location
""")