# Databricks notebook source
import pyspark.sql.functions as F

# COMMAND ----------

# MAGIC %md
# MAGIC ## Import Utils

# COMMAND ----------

# DBTITLE 1,Gold AGG Functions
# MAGIC %run /Workspace/Repos/mariobgallardo@gmail.com/bees_breweries_case/databricks/sl_breweries/utils/gold_agg

# COMMAND ----------

# DBTITLE 1,DQ
# MAGIC %run /Workspace/Repos/mariobgallardo@gmail.com/bees_breweries_case/databricks/sl_breweries/utils/dq

# COMMAND ----------

# MAGIC %md
# MAGIC ## Usage

# COMMAND ----------

# DBTITLE 1,Data aggregation
"""
    Gold table will be generated by aggregating the silver table by country, state, city, and brewery type.
    The silver table will be filtered to remove records with encoding issues and records without an address. (Business Definition)
"""

df_silver = spark.table("md_silver.tb_dim_brewery")

df_gold = build_gold(df_silver)

# COMMAND ----------

# DBTITLE 1,Validation
"""
    This step is responsible for validating the data quality of the Gold table.
    - First validation is performed by checking if there are breweries records;
    - Second validation is performed by checking if there are any group keys with null;
"""

# Check if the dataframe is empty
validate_non_empty(df_gold, "Empty aggregation (Gold)")

# Check if there are any values in the 'brewery_count'
if df_gold.filter("brewery_count <= 0").count() > 0:
    raise Exception("Invalid brewery_count <= 0 found in Gold")

# Check if there are any null values in the group keys
null_key_rows = df_gold.filter("country is null OR state is null OR brewery_type is null").count()
if null_key_rows > 0:
    print(f"[WARN] Gold has {null_key_rows} rows with null keys")

# COMMAND ----------

# DBTITLE 1,Save: tb_agg_brewery_location
# Saving with FULL REFRESH on Gold Table
(
    df_gold
    .write
    .format("delta")
    .mode("overwrite")
    .saveAsTable("md_gold.tb_agg_brewery_location")
)

# COMMAND ----------

# DBTITLE 1,Optmize Gold
# MAGIC %sql
# MAGIC OPTIMIZE md_gold.tb_agg_brewery_location;
